import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const {data: sessionData} = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-[calc(100vh-4rem)] flex-col items-center justify-center bg-gradient-to-br from-[#283c86] to-[#45a247]">
        {!sessionData && (
          // eslint-disable-next-line @typescript-eslint/no-misused-promises
          <button onClick={sessionData ? () => signOut() : () => signIn('email')} 
          className="rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover-bg-black/20">
            Sign in With Google
          </button>
        )}
      </div>
    </>
  );
};

export default Home;
